services:
  - type: web
    name: my-fastapi-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app_main:app --host 0.0.0.0 --port $PORT"
